[package]
name = "sprite-game"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = "*" #{version="0.10.0", features=["nightly"]}
nalgebra = "0.18.1"
serde = "1.0"
regex = "1.3"

[features]
default = ["metal"]
vulkan = ["amethyst/vulkan"]
metal = ["amethyst/metal"]
